In [1]:
import pandas as pd

# Read the CSV and Perform Basic Data Cleaning

In [2]:
df = pd.read_csv("../data/exoplanet_data.csv")
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df.head()

koi_disposition  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  \
0       CONFIRMED              0              0              0              0   
1  FALSE POSITIVE              0              1              0              0   
2  FALSE POSITIVE              0              1              0              0   
3       CONFIRMED              0              0              0              0   
4       CONFIRMED              0              0              0              0   

   koi_period  koi_period_err1  koi_period_err2  koi_time0bk  \
0   54.418383     2.479000e-04    -2.479000e-04   162.513840   
1   19.899140     1.490000e-05    -1.490000e-05   175.850252   
2    1.736952     2.630000e-07    -2.630000e-07   170.307565   
3    2.525592     3.760000e-06    -3.760000e-06   171.595550   
4    4.134435     1.050000e-05    -1.050000e-05   172.979370   

   koi_time0bk_err1  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \
0          0.003520  ...             -81      4.467           0.064   
1          0.000581  ...            -176      4.544           0.044   
2          0.000115  ...            -174      4.564           0.053   
3          0.001130  ...            -211      4.438           0.070   
4          0.001900  ...            -232      4.486           0.054   

   koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
0          -0.096     0.927          0.105         -0.061  291.93423   
1          -0.176     0.868          0.233         -0.078  297.00482   
2          -0.168     0.791          0.201         -0.067  285.53461   
3          -0.210     1.046          0.334         -0.133  288.75488   
4          -0.229     0.972          0.315         -0.105  296.28613   

         dec  koi_kepmag  
0  48.141651      15.347  
1  48.134129      15.436  
2  48.285210      15.597  
3  48.226200      15.509  
4  48.224670      15.714  

[5 rows x 41 columns]

In [3]:
df.tail()

koi_disposition  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  \
6986  FALSE POSITIVE              0              0              0   
6987  FALSE POSITIVE              0              1              1   
6988       CANDIDATE              0              0              0   
6989  FALSE POSITIVE              0              0              1   
6990  FALSE POSITIVE              0              0              1   

      koi_fpflag_ec  koi_period  koi_period_err1  koi_period_err2  \
6986              1    8.589871     1.846000e-04    -1.846000e-04   
6987              0    0.527699     1.160000e-07    -1.160000e-07   
6988              0    1.739849     1.780000e-05    -1.780000e-05   
6989              0    0.681402     2.430000e-06    -2.430000e-06   
6990              1    4.856035     6.360000e-05    -6.360000e-05   

      koi_time0bk  koi_time0bk_err1  ...  koi_steff_err2  koi_slogg  \
6986   132.016100           0.01570  ...            -152      4.296   
6987   131.705093           0.00017  ...            -166      4.529   
6988   133.001270           0.00769  ...            -220      4.444   
6989   132.181750           0.00285  ...            -236      4.447   
6990   135.993300           0.01080  ...            -225      4.385   

      koi_slogg_err1  koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2  \
6986           0.231          -0.189     1.088          0.313         -0.228   
6987           0.035          -0.196     0.903          0.237         -0.079   
6988           0.056          -0.224     1.031          0.341         -0.114   
6989           0.056          -0.224     1.041          0.341         -0.114   
6990           0.054          -0.216     1.193          0.410         -0.137   

             ra        dec  koi_kepmag  
6986  298.74921  46.973351      14.478  
6987  297.18875  47.093819      14.082  
6988  286.50937  47.163219      14.757  
6989  294.16489  47.176281      15.385  
6990  297.00977  47.121021      14.826  

[5 rows x 41 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6991 entries, 0 to 6990
Data columns (total 41 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   koi_disposition    6991 non-null   object 
 1   koi_fpflag_nt      6991 non-null   int64  
 2   koi_fpflag_ss      6991 non-null   int64  
 3   koi_fpflag_co      6991 non-null   int64  
 4   koi_fpflag_ec      6991 non-null   int64  
 5   koi_period         6991 non-null   float64
 6   koi_period_err1    6991 non-null   float64
 7   koi_period_err2    6991 non-null   float64
 8   koi_time0bk        6991 non-null   float64
 9   koi_time0bk_err1   6991 non-null   float64
 10  koi_time0bk_err2   6991 non-null   float64
 11  koi_impact         6991 non-null   float64
 12  koi_impact_err1    6991 non-null   float64
 13  koi_impact_err2    6991 non-null   float64
 14  koi_duration       6991 non-null   float64
 15  koi_duration_err1  6991 non-null   float64
 16  koi_duration_err2  6991 

# Select your features (columns)

In [5]:
# Set features. This will also be used as x values.
target = df["koi_disposition"]
target_names = ['CANDIDATE','CONFIRMED','FALSE POSITIVE']
features = df.drop("koi_disposition", axis=1)
feature_names=features.columns

# Create a Train Test Split

Use `koi_disposition` for the y values

In [6]:
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(target)
encoded_y = label_encoder.transform(target)
encoded_y

array([1, 2, 2, ..., 0, 2, 2])

In [7]:
# Step 2: One-hot encoding
one_hot_y = to_categorical(encoded_y)
one_hot_y

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.]], dtype=float32)

In [8]:
from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(features, encoded_y, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(features, one_hot_y, random_state=42)
X_train.shape, y_train.shape

((5243, 40), (5243, 3))

# Pre-processing

Scale the data using the MinMaxScaler and perform some feature selection

In [9]:
# Scale the data
from sklearn.preprocessing import MinMaxScaler
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [10]:
from sklearn.ensemble import RandomForestClassifier
 # Create a random forest classifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train_scaled, y_train)
rf.score(X_train_scaled, y_train)

1.0

In [11]:
importances = rf.feature_importances_
rf_feature_importance=sorted(zip(importances, feature_names), reverse=True)
rf_ranked_feature=[a[1] for a in rf_feature_importance]
rf_ranked_feature[:10]

['koi_fpflag_co',
 'koi_fpflag_nt',
 'koi_fpflag_ss',
 'koi_model_snr',
 'koi_prad',
 'koi_duration_err2',
 'koi_fpflag_ec',
 'koi_prad_err2',
 'koi_steff_err1',
 'koi_duration_err1']

In [12]:
import numpy as np
rf_ranked_list=np.argsort(np.flip(importances))
rf_ranked_list[:10]
# X_train_scaled=X_train_scaled[:,rf_ranked_list[:10]]

array([12,  3,  7,  8,  5,  6, 11,  0, 27, 28], dtype=int64)

In [13]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train_scaled, y_train)
clf.score(X_train_scaled, y_train)

1.0

In [14]:
importances = clf.feature_importances_
clf_feature_importance=sorted(zip(importances, feature_names), reverse=True)
clf_ranked_feature=[a[1] for a in clf_feature_importance]
clf_ranked_feature[:10]

['koi_fpflag_nt',
 'koi_fpflag_co',
 'koi_fpflag_ss',
 'koi_model_snr',
 'koi_fpflag_ec',
 'koi_impact',
 'dec',
 'koi_time0bk',
 'koi_prad',
 'koi_srad_err1']

# Train the Model



In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Create model and add layers
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=40))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=3, activation='softmax'))

# Compile and fit the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(
    X_train_scaled,
    y_train,
    epochs=100,
    shuffle=True,
    verbose=2
)

Epoch 1/100
164/164 - 0s - loss: 0.5583 - accuracy: 0.7318
Epoch 2/100
164/164 - 0s - loss: 0.3667 - accuracy: 0.8184
Epoch 3/100
164/164 - 0s - loss: 0.3490 - accuracy: 0.8266
Epoch 4/100
164/164 - 0s - loss: 0.3417 - accuracy: 0.8287
Epoch 5/100
164/164 - 0s - loss: 0.3343 - accuracy: 0.8323
Epoch 6/100
164/164 - 0s - loss: 0.3283 - accuracy: 0.8407
Epoch 7/100
164/164 - 0s - loss: 0.3188 - accuracy: 0.8518
Epoch 8/100
164/164 - 0s - loss: 0.3197 - accuracy: 0.8510
Epoch 9/100
164/164 - 0s - loss: 0.3132 - accuracy: 0.8560
Epoch 10/100
164/164 - 0s - loss: 0.3144 - accuracy: 0.8514
Epoch 11/100
164/164 - 0s - loss: 0.3060 - accuracy: 0.8552
Epoch 12/100
164/164 - 0s - loss: 0.3047 - accuracy: 0.8564
Epoch 13/100
164/164 - 0s - loss: 0.3006 - accuracy: 0.8621
Epoch 14/100
164/164 - 0s - loss: 0.3018 - accuracy: 0.8611
Epoch 15/100
164/164 - 0s - loss: 0.2905 - accuracy: 0.8659
Epoch 16/100
164/164 - 0s - loss: 0.2938 - accuracy: 0.8625
Epoch 17/100
164/164 - 0s - loss: 0.2973 - accura

In [16]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

55/55 - 0s - loss: 0.2539 - accuracy: 0.8993
Normal Neural Network - Loss: 0.2539297044277191, Accuracy: 0.8993135094642639


In [17]:
encoded_predictions = np.argmax(model.predict(X_test_scaled), axis=-1)
prediction_labels = label_encoder.inverse_transform(encoded_predictions)
prediction_labels

array(['FALSE POSITIVE', 'CANDIDATE', 'FALSE POSITIVE', ..., 'CONFIRMED',
       'CANDIDATE', 'CANDIDATE'], dtype=object)

In [18]:
encoded_ytest = np.argmax(y_test, axis=-1)
decoded_ytest = label_encoder.inverse_transform(encoded_ytest)
decoded_ytest

array(['FALSE POSITIVE', 'CANDIDATE', 'FALSE POSITIVE', ..., 'CONFIRMED',
       'CONFIRMED', 'CONFIRMED'], dtype=object)

In [19]:
from sklearn.metrics import classification_report
print(classification_report(decoded_ytest, prediction_labels))

                precision    recall  f1-score   support

     CANDIDATE       0.81      0.78      0.79       411
     CONFIRMED       0.82      0.84      0.83       484
FALSE POSITIVE       0.98      0.99      0.99       853

      accuracy                           0.90      1748
     macro avg       0.87      0.87      0.87      1748
  weighted avg       0.90      0.90      0.90      1748



# Save the Model

In [20]:
model.save("deep_learning_model.h5")